services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DB_PASSWORD
      MYSQL_DATABASE: hospital_system
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d